# Generated by Django 3.2.8 on 2021-10-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ly3000App', '0006_auto_20211026_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projectCreater',
        ),
    ]
